// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as gax from 'google-gax';
import {
  APICallback,
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
  PaginationCallback,
  PaginationResponse,
} from 'google-gax';
import * as path from 'path';

import {Transform} from 'stream';
import * as protosTypes from '../../protos/protos';
import * as gapicConfig from './executions_client_config.json';

const version = require('../../../package.json').version;

/**
 *  Manages workflow executions.
 * @class
 * @memberof v1alpha1
 */
export class ExecutionsClient {
  private _descriptors: Descriptors = {page: {}, stream: {}, longrunning: {}};
  private _innerApiCalls: {[name: string]: Function};
  private _pathTemplates: {[name: string]: gax.PathTemplate};
  private _terminated = false;
  auth: gax.GoogleAuth;
  executionsStub: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of ExecutionsClient.
   *
   * @param {object} [options] - The configuration object. See the subsequent
   *   parameters for more details.
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {function} [options.promise] - Custom promise module to use instead
   *     of native Promises.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   */

  constructor(opts?: ClientOptions) {
    // Ensure that options include the service address and port.
    const staticMembers = this.constructor as typeof ExecutionsClient;
    const servicePath =
      opts && opts.servicePath
        ? opts.servicePath
        : opts && opts.apiEndpoint
        ? opts.apiEndpoint
        : staticMembers.servicePath;
    const port = opts && opts.port ? opts.port : staticMembers.port;

    if (!opts) {
      opts = {servicePath, port};
    }
    opts.servicePath = opts.servicePath || servicePath;
    opts.port = opts.port || port;
    opts.clientConfig = opts.clientConfig || {};

    const isBrowser = typeof window !== 'undefined';
    if (isBrowser) {
      opts.fallback = true;
    }
    // If we are in browser, we are already using fallback because of the
    // "browser" field in package.json.
    // But if we were explicitly requested to use fallback, let's do it now.
    const gaxModule = !isBrowser && opts.fallback ? gax.fallback : gax;

    // Create a `gaxGrpc` object, with any grpc-specific options
    // sent to the client.
    opts.scopes = (this.constructor as typeof ExecutionsClient).scopes;
    const gaxGrpc = new gaxModule.GrpcClient(opts);

    // Save the auth object to the client, for use by other methods.
    this.auth = gaxGrpc.auth as gax.GoogleAuth;

    // Determine the client header string.
    const clientHeader = [`gax/${gaxModule.version}`, `gapic/${version}`];
    if (typeof process !== 'undefined' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    // For Node.js, pass the path to JSON proto file.
    // For browsers, pass the JSON content.

    const nodejsProtoPath = path.join(
      __dirname,
      '..',
      '..',
      'protos',
      'protos.json'
    );
    const protos = gaxGrpc.loadProto(
      opts.fallback ? require('../../protos/protos.json') : nodejsProtoPath
    );

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this._pathTemplates = {
      executionPathTemplate: new gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/workflows/{workflow}/executions/{execution}'
      ),
    };

    // Some of the methods on this service return "paged" results,
    // (e.g. 50 results at a time, with tokens to get subsequent
    // pages). Denote the keys used for pagination and results.
    this._descriptors.page = {
      listExecutions: new gaxModule.PageDescriptor(
        'pageToken',
        'nextPageToken',
        'executions'
      ),
    };

    // Put together the default options sent with requests.
    const defaults = gaxGrpc.constructSettings(
      'google.cloud.workflows.executions.v1alpha1.Executions',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')}
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this._innerApiCalls = {};

    // Put together the "service stub" for
    // google.cloud.workflows.executions.v1alpha1.Executions.
    this.executionsStub = gaxGrpc.createStub(
      opts.fallback
        ? (protos as protobuf.Root).lookupService(
            'google.cloud.workflows.executions.v1alpha1.Executions'
          )
        : // tslint:disable-next-line no-any
          (protos as any).google.cloud.workflows.executions.v1alpha1.Executions,
      opts
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const executionsStubMethods = [
      'listExecutions',
      'createExecution',
      'cancelExecution',
      'getExecution',
    ];

    for (const methodName of executionsStubMethods) {
      const innerCallPromise = this.executionsStub.then(
        stub => (...args: Array<{}>) => {
          if (this._terminated) {
            return Promise.reject('The client has already been closed.');
          }
          return stub[methodName].apply(stub, args);
        },
        (err: Error | null | undefined) => () => {
          throw err;
        }
      );

      const apiCall = gaxModule.createApiCall(
        innerCallPromise,
        defaults[methodName],
        this._descriptors.page[methodName] ||
          this._descriptors.stream[methodName] ||
          this._descriptors.longrunning[methodName]
      );

      this._innerApiCalls[methodName] = (
        argument: {},
        callOptions?: CallOptions,
        callback?: APICallback
      ) => {
        return apiCall(argument, callOptions, callback);
      };
    }
  }

  /**
   * The DNS address for this API service.
   */
  static get servicePath() {
    return 'workflowexecutions.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath(),
   * exists for compatibility reasons.
   */
  static get apiEndpoint() {
    return 'workflowexecutions.googleapis.com';
  }

  /**
   * The port for this API service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   */
  static get scopes() {
    return ['https://www.googleapis.com/auth/cloud-platform'];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @param {function(Error, string)} callback - the callback to
   *   be called with the current project Id.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  createExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  >;
  createExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest
      | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Creates a new workflow execution using the latest version of the workflow.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. Name of the workflow for which an execution should be created,
   *   for example, "projects/project1/locations/us-central1/workflows/workflow1".
   * @param {google.cloud.workflows.executions.v1alpha1.Execution} request.execution
   *   Required. Execution to be created.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  createExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
          | protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest
          | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest
      | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.ICreateExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      parent: request.parent || '',
    });
    return this._innerApiCalls.createExecution(request, options, callback);
  }
  cancelExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  >;
  cancelExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest
      | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Cancels a workflow execution of the given name.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. Name of the workflow execution which should be cancelled.
   *   "projects/project1/locations/us-central1/workflows/workflow1/executions/execution1"
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  cancelExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
          | protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest
          | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest
      | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.ICancelExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      name: request.name || '',
    });
    return this._innerApiCalls.cancelExecution(request, options, callback);
  }
  getExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  >;
  getExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest
      | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Returns a workflow execution with the specified name.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. Name of the workflow execution which information should be
   *   retrieved, for example,
   *   "projects/project1/locations/us-central1/workflows/workflow1/executions/execution1"
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  getExecution(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
          | protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest
          | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      | protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest
      | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution,
      (
        | protosTypes.google.cloud.workflows.executions.v1alpha1.IGetExecutionRequest
        | undefined
      ),
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      name: request.name || '',
    });
    return this._innerApiCalls.getExecution(request, options, callback);
  }

  listExecutions(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution[],
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest | null,
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsResponse
    ]
  >;
  listExecutions(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution[],
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest | null,
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsResponse
    >
  ): void;
  /**
   * Returns a list of workflow executions which belong to the workflow with
   * the specified name. The method returns executions from all workflow
   * versions.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. Name of the workflow from which the executions should be listed,
   *   for example, "projects/project1/locations/us-central1/workflows/workflow1".
   * @param {number} request.pageSize
   *   Maximum number of workflow executions to return per call.
   * @param {string} request.pageToken
   *   The value returned by the last
   *   `ListExecutionsResponse` indicates that
   *   this is a continuation of a prior `ListExecutions` call, and that
   *   the system should return the next page of data.
   * @param {string} request.filter
   *   The filter expression.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is Array of [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution}.
   *   The client library support auto-pagination by default: it will call the API as many
   *   times as needed and will merge results from all the pages into this array.
   *
   *   When autoPaginate: false is specified through options, the array has three elements.
   *   The first element is Array of [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution} that corresponds to
   *   the one page received from the API server.
   *   If the second element is not null it contains the request object of type [ListExecutionsRequest]{@link google.cloud.workflows.executions.v1alpha1.ListExecutionsRequest}
   *   that can be used to obtain the next page of the results.
   *   If it is null, the next page does not exist.
   *   The third element contains the raw response received from the API server. Its type is
   *   [ListExecutionsResponse]{@link google.cloud.workflows.executions.v1alpha1.ListExecutionsResponse}.
   *
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  listExecutions(
    request: protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution[],
          protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest | null,
          protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsResponse
        >,
    callback?: Callback<
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution[],
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest | null,
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsResponse
    >
  ): Promise<
    [
      protosTypes.google.cloud.workflows.executions.v1alpha1.IExecution[],
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest | null,
      protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsResponse
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      parent: request.parent || '',
    });
    return this._innerApiCalls.listExecutions(request, options, callback);
  }

  /**
   * Equivalent to {@link listExecutions}, but returns a NodeJS Stream object.
   *
   * This fetches the paged responses for {@link listExecutions} continuously
   * and invokes the callback registered for 'data' event for each element in the
   * responses.
   *
   * The returned object has 'end' method when no more elements are required.
   *
   * autoPaginate option will be ignored.
   *
   * @see {@link https://nodejs.org/api/stream.html}
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. Name of the workflow from which the executions should be listed,
   *   for example, "projects/project1/locations/us-central1/workflows/workflow1".
   * @param {number} request.pageSize
   *   Maximum number of workflow executions to return per call.
   * @param {string} request.pageToken
   *   The value returned by the last
   *   `ListExecutionsResponse` indicates that
   *   this is a continuation of a prior `ListExecutions` call, and that
   *   the system should return the next page of data.
   * @param {string} request.filter
   *   The filter expression.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Stream}
   *   An object stream which emits an object representing [Execution]{@link google.cloud.workflows.executions.v1alpha1.Execution} on 'data' event.
   */
  listExecutionsStream(
    request?: protosTypes.google.cloud.workflows.executions.v1alpha1.IListExecutionsRequest,
    options?: gax.CallOptions | {}
  ): Transform {
    request = request || {};
    const callSettings = new gax.CallSettings(options);
    return this._descriptors.page.listExecutions.createStream(
      this._innerApiCalls.listExecutions as gax.GaxCall,
      request,
      callSettings
    );
  }
  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified execution resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} workflow
   * @param {string} execution
   * @returns {string} Resource name string.
   */
  executionPath(
    project: string,
    location: string,
    workflow: string,
    execution: string
  ) {
    return this._pathTemplates.executionPathTemplate.render({
      project,
      location,
      workflow,
      execution,
    });
  }

  /**
   * Parse the project from Execution resource.
   *
   * @param {string} executionName
   *   A fully-qualified path representing Execution resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromExecutionName(executionName: string) {
    return this._pathTemplates.executionPathTemplate.match(executionName)
      .project;
  }

  /**
   * Parse the location from Execution resource.
   *
   * @param {string} executionName
   *   A fully-qualified path representing Execution resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromExecutionName(executionName: string) {
    return this._pathTemplates.executionPathTemplate.match(executionName)
      .location;
  }

  /**
   * Parse the workflow from Execution resource.
   *
   * @param {string} executionName
   *   A fully-qualified path representing Execution resource.
   * @returns {string} A string representing the workflow.
   */
  matchWorkflowFromExecutionName(executionName: string) {
    return this._pathTemplates.executionPathTemplate.match(executionName)
      .workflow;
  }

  /**
   * Parse the execution from Execution resource.
   *
   * @param {string} executionName
   *   A fully-qualified path representing Execution resource.
   * @returns {string} A string representing the execution.
   */
  matchExecutionFromExecutionName(executionName: string) {
    return this._pathTemplates.executionPathTemplate.match(executionName)
      .execution;
  }

  /**
   * Terminate the GRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   */
  close(): Promise<void> {
    if (!this._terminated) {
      return this.executionsStub.then(stub => {
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
}
